@baseUrl=http://localhost:3000/api/v1
@todoId={{todos.response.body.data[0].id}}

### Get all todos
# @name todos
GET {{baseUrl}}/todos
Content-Type: application/json

### Get todo
GET {{baseUrl}}/todos/{{todoId}}
Content-Type: application/json

### Create todo
# @name createTodo
POST {{baseUrl}}/todos
Content-Type: application/json

{
    "title": "test todo",
    "completed": false
}

### Update todo
PUT {{baseUrl}}/todos/{{todoId}}
Content-Type: application/json

{
    "id": "{{todoId}}",
    "created_at": "2024-06-06T00:39:58.000997+08:00",
    "updated_at": "2024-06-06T00:39:58.000997+08:00",
    "title": "todo 1",
    "completed": true
}

### Delete todo
DELETE {{baseUrl}}/todos/{{todoId}}
Content-Type: application/json
